"""add_paper_trade_fields

Revision ID: b15be4c1a51d
Revises: b18d9eb31e74
Create Date: 2026-02-28 03:07:41.824343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15be4c1a51d'
down_revision: Union[str, Sequence[str], None] = 'b18d9eb31e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('paper_trade_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('trades', sa.Column('is_paper_trade', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'is_paper_trade')
    op.drop_column('accounts', 'paper_trade_enabled')
    # ### end Alembic commands ###
